---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: htop

  - name: copy wallpaper file
    copy:
      src: files/black.jpg
      dest: $HOME/Pictures/wallpapers.jpg
      owner: root
      group: root
     
  - name: copy .zshrc file
    copy:
      src: files/bashrc
      dest: $HOME/.zshrc
      owner: root
      group: root

  
